# -*- coding: utf-8 -*-
"""Data_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q6Mm7fGa0xf8KrQQApWK-bppnS1sYsG1
"""

import pandas as pd
data={'name':['tom','shubham','ankit','anuj'],'Age':[20,19,18,17]}
df=pd.DataFrame(data)
print(df)

import pandas as pd
lst=['Greek','for','greek','is','portal','for','greek']
df=pd.DataFrame(lst)
print(df)

import statistics


numbers = [10, 20, 20, 30, 40, 50, 20]

# Mean
mean_value = statistics.mean(numbers)

# Median
median_value = statistics.median(numbers)

# Mode
mode_value = statistics.mode(numbers)

# Variance
variance_value = statistics.variance(numbers)  # Sample variance

# Standard Deviation
std_dev_value = statistics.stdev(numbers)  # Sample standard deviation

print("Numbers:", numbers)
print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_dev_value)

data={'Name':['Jat',' Princi', 'Gaurav ','Anuj'],

'Age':[127, 24, 22, 32],

'Address' :['Delhi', 'Kanpur', 'Allahabad' 'Kannauj'],

'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df= pd.DataFrame(data)

print(df[['Name', 'Qualification']])

import pandas as pd
data =pd.read_csv("/content/nba.csv",index_col="Name")

first=data.loc["Avery Bradley"]
second=data.loc["R.J.Humter"]

print(first,"\n\n\n",second)

import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50, 60])

print("Original Array:")
print(arr)

# 1️⃣ Find Sum and Mean
array_sum = np.sum(arr)
array_mean = np.mean(arr)

print("\nSum:", array_sum)
print("Mean:", array_mean)

# 2️⃣ Find Maximum and Minimum
array_max = np.max(arr)
array_min = np.min(arr)

print("\nMaximum:", array_max)
print("Minimum:", array_min)

# 3️⃣ Reshape the Array (1D → 2D)
reshaped_arr = arr.reshape(2, 3)

print("\nReshaped Array (2x3):")
print(reshaped_arr)

# 4️⃣ Element-wise Multiplication
# Multiply array by 2
elementwise_mult = arr * 2

print("\nElement-wise Multiplication (arr * 2):")
print(elementwise_mult)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Sample Data (X = independent variable, y = dependent variable)
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
y = np.array([2, 4, 5, 4, 5])

# Create model
model = LinearRegression()

# Train model
model.fit(X, y)

# Predict
y_pred = model.predict(X)

# Print equation
print("Slope (m):", model.coef_[0])
print("Intercept (b):", model.intercept_)
print("Equation: y =", model.coef_[0], "x +", model.intercept_)

# Plot
plt.scatter(X, y, color='blue')
plt.plot(X, y_pred, color='red')
plt.xlabel("X")
plt.ylabel("y")
plt.title("Simple Linear Regression")
plt.show()